# Generated by Django 3.1.7 on 2021-03-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                ('country', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('points', models.IntegerField()),
                (
                    'price',
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ('variety', models.CharField(max_length=255)),
                ('winery', models.CharField(max_length=255)),
            ],
        ),
    ]
