# Generated by Django 3.1.7 on 2021-04-01 20:18

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import BtreeGinExtension, TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        TrigramExtension(),
        BtreeGinExtension(),
        migrations.AddIndex(
            model_name='wine',
            index=django.contrib.postgres.indexes.GinIndex(
                fields=['description', 'variety', 'winery'],
                name='desc_var_win_gin_idx',
                opclasses=['gin_trgm_ops', 'gin_trgm_ops', 'gin_trgm_ops'],
            ),
        ),
    ]
