# Generated by Django 3.1.7 on 2021-04-01 21:39
from django.db import migrations

from catalog.models import calculate_wine_search_vector


def update_search_vector(apps, schema_editor):
    wine_model = apps.get_model('catalog', 'Wine')
    wine_model.objects.all().update(search_vector=calculate_wine_search_vector())


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_search_vector'),
    ]

    operations = [
        migrations.RunPython(update_search_vector, elidable=True),
    ]
